#配置数据库
spring:
  datasource:
    username: root
    password: cyl1391212
    url: jdbc:mysql://localhost:3306/delicious?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置Mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: edu.swjtuhc.demo.mapper
