#配置数据库
spring:
datasource:
username: root
password: cyl1391212
url: "jdbc:mysql://localhost:3306/test?useSSL=false&amp;serverTimezone=GMT%2B8&amp;allowPublicKeyRetrieval=true"
driver-class-name: com.mysql.cj.jdbc.Driver
#配置Mybatis
mybayis:
mapper-locations: classpath:mapper/*.xml
type-aliases-package: edu.swjtuhc.demo.mapper
